/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.openwims.UI.Editors;

import org.openwims.Objects.Lexicon.DependencySet;

/**
 *
 * @author jesseenglish
 */
public class DependencySetEditorJPanel extends javax.swing.JPanel {
    
    private DependencySet set;

    /**
     * Creates new form DependencySetEditorJPanel
     */
    public DependencySetEditorJPanel(DependencySet set) {
        initComponents();
        this.set = set;
        
        this.LabelFTextField.setText(this.set.label);
        this.OptionalFCheckBox.setSelected(this.set.optional);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        LabelFTextField = new com.jesseenglish.swingftfy.extensions.FTextField();
        OptionalFCheckBox = new com.jesseenglish.swingftfy.extensions.FCheckBox();

        setLayout(new java.awt.GridBagLayout());

        LabelFTextField.setHintText("label");
        LabelFTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LabelFTextFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        add(LabelFTextField, gridBagConstraints);

        OptionalFCheckBox.setSelected(true);
        OptionalFCheckBox.setText("optional");
        OptionalFCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptionalFCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(OptionalFCheckBox, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void LabelFTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LabelFTextFieldKeyReleased
        this.set.label = this.LabelFTextField.getText().trim();
    }//GEN-LAST:event_LabelFTextFieldKeyReleased

    private void OptionalFCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptionalFCheckBoxActionPerformed
        this.set.optional = this.OptionalFCheckBox.isSelected();
    }//GEN-LAST:event_OptionalFCheckBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jesseenglish.swingftfy.extensions.FTextField LabelFTextField;
    private com.jesseenglish.swingftfy.extensions.FCheckBox OptionalFCheckBox;
    // End of variables declaration//GEN-END:variables
}
