/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.openwims.UI.Editors;

import org.openwims.Objects.Lexicon.Sense;

/**
 *
 * @author jesseenglish
 */
public class ExampleEditorJPanel extends javax.swing.JPanel {
    
    private Sense sense;

    /**
     * Creates new form DefinitionEditorJPanel
     */
    public ExampleEditorJPanel(Sense sense) {
        initComponents();
        this.sense = sense;
        
        this.ExampleFTextField.setText(sense.getExample());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ExampleFTextField = new com.jesseenglish.swingftfy.extensions.FTextField();

        setLayout(new java.awt.GridBagLayout());

        ExampleFTextField.setHintText("example");
        ExampleFTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ExampleFTextFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        add(ExampleFTextField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void ExampleFTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ExampleFTextFieldKeyReleased
        this.sense.setExample(this.ExampleFTextField.getText().trim());
    }//GEN-LAST:event_ExampleFTextFieldKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jesseenglish.swingftfy.extensions.FTextField ExampleFTextField;
    // End of variables declaration//GEN-END:variables
}
