/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.openwims.UI.Editors;

import org.openwims.Objects.Lexicon.Meaning;

/**
 *
 * @author jesseenglish
 */
public class MeaningEditorJPanel extends javax.swing.JPanel {
    
    private Meaning meaning;

    /**
     * Creates new form MeaningEditorJPanel
     */
    public MeaningEditorJPanel(Meaning meaning) {
        initComponents();
        this.meaning = meaning;
        
        this.TargetFTextField.setText(meaning.target);
        this.RelationFTextField.setText(meaning.relation);
        this.WIMFTextField.setText(meaning.wim);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        TargetFTextField = new com.jesseenglish.swingftfy.extensions.FTextField();
        RelationFTextField = new com.jesseenglish.swingftfy.extensions.FTextField();
        WIMFTextField = new com.jesseenglish.swingftfy.extensions.FTextField();

        setLayout(new java.awt.GridBagLayout());

        TargetFTextField.setHintText("target");
        TargetFTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TargetFTextFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        add(TargetFTextField, gridBagConstraints);

        RelationFTextField.setHintText("relation");
        RelationFTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RelationFTextFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(RelationFTextField, gridBagConstraints);

        WIMFTextField.setHintText("wim");
        WIMFTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                WIMFTextFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(WIMFTextField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void TargetFTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TargetFTextFieldKeyReleased
        this.meaning.target = this.TargetFTextField.getText().trim();
    }//GEN-LAST:event_TargetFTextFieldKeyReleased

    private void RelationFTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RelationFTextFieldKeyReleased
        this.meaning.relation = this.RelationFTextField.getText().trim();
    }//GEN-LAST:event_RelationFTextFieldKeyReleased

    private void WIMFTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WIMFTextFieldKeyReleased
        this.meaning.wim = this.WIMFTextField.getText().trim();
    }//GEN-LAST:event_WIMFTextFieldKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jesseenglish.swingftfy.extensions.FTextField RelationFTextField;
    private com.jesseenglish.swingftfy.extensions.FTextField TargetFTextField;
    private com.jesseenglish.swingftfy.extensions.FTextField WIMFTextField;
    // End of variables declaration//GEN-END:variables
}
