/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.openwims.UI;

import org.openwims.Objects.Lexicon.Dependency;

/**
 *
 * @author jesseenglish
 */
public class DependencyEditorJPanel extends javax.swing.JPanel {
    
    private Dependency dependency;

    /**
     * Creates new form DependencyEditorJPanel
     */
    public DependencyEditorJPanel(Dependency dependency) {
        this.dependency = dependency;
        initComponents();
        
        this.TypeJTextField.setText(this.dependency.type);
        this.GovJTextField.setText(this.dependency.governor);
        this.DepJTextField.setText(this.dependency.dependent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        TypeJTextField = new com.jesseenglish.swingftfy.extensions.FTextField();
        GovJTextField = new com.jesseenglish.swingftfy.extensions.FTextField();
        DepJTextField = new com.jesseenglish.swingftfy.extensions.FTextField();

        setLayout(new java.awt.GridBagLayout());

        TypeJTextField.setHintText("dependency type");
        TypeJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TypeJTextFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        add(TypeJTextField, gridBagConstraints);

        GovJTextField.setHintText("governor");
        GovJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                GovJTextFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(GovJTextField, gridBagConstraints);

        DepJTextField.setHintText("dependent");
        DepJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DepJTextFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(DepJTextField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void TypeJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TypeJTextFieldKeyReleased
        this.dependency.type = this.TypeJTextField.getText().trim();
    }//GEN-LAST:event_TypeJTextFieldKeyReleased

    private void GovJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GovJTextFieldKeyReleased
        this.dependency.governor = this.GovJTextField.getText().trim();
    }//GEN-LAST:event_GovJTextFieldKeyReleased

    private void DepJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DepJTextFieldKeyReleased
        this.dependency.dependent = this.DepJTextField.getText().trim();
    }//GEN-LAST:event_DepJTextFieldKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jesseenglish.swingftfy.extensions.FTextField DepJTextField;
    private com.jesseenglish.swingftfy.extensions.FTextField GovJTextField;
    private com.jesseenglish.swingftfy.extensions.FTextField TypeJTextField;
    // End of variables declaration//GEN-END:variables
}
