/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.openwims.UI;

/**
 *
 * @author jesseenglish
 */
public class ExpectationEditorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ExpectationEditorJPanel
     */
    public ExpectationEditorJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        SpecificationJTextField = new com.jesseenglish.swingftfy.extensions.FTextField();
        ExpectationJTextField = new com.jesseenglish.swingftfy.extensions.FTextField();

        setLayout(new java.awt.GridBagLayout());

        SpecificationJTextField.setHintText("specification");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        add(SpecificationJTextField, gridBagConstraints);

        ExpectationJTextField.setHintText("expectation");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(ExpectationJTextField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jesseenglish.swingftfy.extensions.FTextField ExpectationJTextField;
    private com.jesseenglish.swingftfy.extensions.FTextField SpecificationJTextField;
    // End of variables declaration//GEN-END:variables

    public String getSpecification() {
        return this.SpecificationJTextField.getText().trim();
    }
    
    public String getExpectation() {
        return this.ExpectationJTextField.getText().trim();
    }

}
