/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.openwims.UI.Editors;

import org.openwims.Objects.Lexicon.Expectation;

/**
 *
 * @author jesseenglish
 */
public class ExpectationEditorJPanel extends javax.swing.JPanel {

    private Expectation expectation;
    
    /**
     * Creates new form ExpectationEditorJPanel
     */
    public ExpectationEditorJPanel(Expectation expectation) {
        initComponents();
        
        this.expectation = expectation;
        
        this.SpecificationJTextField.setText(expectation.getSpecification());
        this.ExpectationJTextField.setText(expectation.getExpectation());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        SpecificationJTextField = new com.jesseenglish.swingftfy.extensions.FTextField();
        ExpectationJTextField = new com.jesseenglish.swingftfy.extensions.FTextField();

        setLayout(new java.awt.GridBagLayout());

        SpecificationJTextField.setHintText("specification");
        SpecificationJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SpecificationJTextFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        add(SpecificationJTextField, gridBagConstraints);

        ExpectationJTextField.setHintText("expectation");
        ExpectationJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ExpectationJTextFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(ExpectationJTextField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void SpecificationJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SpecificationJTextFieldKeyReleased
        this.expectation.setSpecification(this.SpecificationJTextField.getText().trim());
    }//GEN-LAST:event_SpecificationJTextFieldKeyReleased

    private void ExpectationJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ExpectationJTextFieldKeyReleased
        this.expectation.setExpectation(this.ExpectationJTextField.getText().trim());
    }//GEN-LAST:event_ExpectationJTextFieldKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jesseenglish.swingftfy.extensions.FTextField ExpectationJTextField;
    private com.jesseenglish.swingftfy.extensions.FTextField SpecificationJTextField;
    // End of variables declaration//GEN-END:variables

}
